import {createClient} from 'npm:@supabase/supabase-js@2';
import {RequestError,canonical,normalizeRecord,managerInput} from './core.mjs';
import builtinModels from './models.json' with {type:'json'};
const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});
const origins=(Deno.env.get('PPL_ALLOWED_ORIGINS')||'https://engseg-pr.github.io').split(',').map(x=>x.trim());
const uuid=(x:unknown)=>typeof x==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(x);
async function checked(q:any){const {data,error}=await q;if(error)throw new RequestError('Operação indisponível. Tente novamente.',503);return data;}
async function hash(bytes:Uint8Array){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function body(req:Request){const reader=req.body?.getReader();if(!reader)throw new RequestError('Pedido vazio.');let n=0;const chunks=[];while(true){const r=await reader.read();if(r.done)break;n+=r.value.length;if(n>20971520){await reader.cancel();throw new RequestError('Pedido excede 20 MB.',413);}chunks.push(r.value);}const out=new Uint8Array(n);let offset=0;for(const c of chunks){out.set(c,offset);offset+=c.length;}try{return {value:JSON.parse(new TextDecoder().decode(out)),n};}catch{throw new RequestError('Formato inválido.');}}
function text(x:unknown,max=160){const s=String(x||'').trim();if(!s||s.length>max)throw new RequestError('Preencha os campos obrigatórios.');return s;}
function logo(x:unknown){if(typeof x!=='string'||x.length>2500000||!/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/]+={0,2}$/.test(x))throw new RequestError('Envie a logo em PNG ou JPEG.');return x;}
function brand(c:any){return {id:c.id,slug:c.slug,name:c.name,version:c.brand_version,logoData:c.logo_data};}
async function company(id?:string,slug?:string){let q=admin.from('ppl_companies').select('*');if(id){if(!uuid(id))throw new RequestError('Empresa inválida.');q=q.eq('id',id);}else q=q.eq('slug',slug||'ppl');const c=await checked(q.maybeSingle());if(!c)throw new RequestError('Empresa não encontrada.',404);return c;}
async function templates(c:any){const custom=await checked(admin.from('ppl_company_models').select('snapshot,kind,active').eq('company_id',c.id));const base=builtinModels.filter((m:any)=>m.reportLayout?.issuer==='VALE'||c.slug==='ppl').map((m:any)=>({snapshot:m,kind:'checklist',active:true}));return [...base,...custom];}
function procedureLayout(input:any,itemCount:number){
 if(!input)return null;if(input.type!=='procedure-table'||input.reviewed!==true)throw new RequestError('Revise o procedimento original antes de salvar.');
 const rows=Number(input.totalRows);if(!Number.isInteger(rows)||rows<itemCount||rows>80)throw new RequestError('Quantidade de linhas do procedimento inválida.');
 if(!Array.isArray(input.guidance)||input.guidance.length>20)throw new RequestError('Orientações inválidas.');
 return {...(input.sourceLogoData?{sourceLogoData:logo(input.sourceLogoData)}:{}),type:'procedure-table',variant:'vale-scaffold-1a',issuer:'VALE',procedureTitle:text(input.procedureTitle,250),procedureCode:text(input.procedureCode,80),revision:text(input.revision,40),revisionDate:text(input.revisionDate,40),annexTitle:text(input.annexTitle,200),sectionTitle:text(input.sectionTitle,80),totalRows:rows,action:text(input.action,250),guidance:input.guidance.map((x:any)=>text(x,3000)),fields:[{name:'v_department',label:'GERÊNCIA',type:'text',required:true},{name:'v_service',label:'SERVIÇO A SER REALIZADO',type:'text',required:true},{name:'v_scaffoldInspector',label:'NOME INSPETOR DE ANDAIMES',type:'staff',required:true},{name:'v_scaffoldEmployee',label:'MATRÍCULA',type:'readonly',required:true},{name:'v_scaffoldDate',label:'DATA DO INSPETOR',type:'date',required:true},{name:'v_dailyDate',label:'DATA DA VERIFICAÇÃO DIÁRIA',type:'date',required:true}]};
}
function photoOrigin(input:any){if(!input)return null;if(input.type!=='photo'||input.reviewed!==true||typeof input.sha256!=='string'||!/^[a-f0-9]{64}$/.test(input.sha256))throw new RequestError('Origem da foto inválida.');return {type:'photo',filename:text(input.filename,500),sha256:input.sha256,reviewed:true};}
function templateInput(b:any){const title=text(b.title,200),equipment=text(b.equipment,160),kind=b.kind;if(!['checklist','inspection'].includes(kind)||!Array.isArray(b.items)||!b.items.length||b.items.length>250)throw new RequestError('Informe o tipo e os itens do modelo.');const reportLayout=procedureLayout(b.reportLayout,b.items.length),origin=photoOrigin(b.photoOrigin);const id='pr-'+crypto.randomUUID(),version='1';const items=b.items.map((x:any,n:number)=>({id:id+'-'+(n+1),category:text(x.category||'Verificação',160),text:text(x.text,4000),sourceNumber:String(n+1)}));return {kind,snapshot:{id,version,title,equipmentName:equipment,equipmentMode:'generic',identificationLabel:reportLayout?'LOCAL/EQUIPAMENTO':'Identificação do equipamento / local',identifiers:reportLayout?.fields||[],requiresWorkerPhoto:true,types:[text(b.inspectionType||'Inspeção conforme necessidade',160)],items,...(reportLayout?{reportLayout}:{}),source:{...(origin?{photoOrigin:origin}:{}),form:text(b.formCode||'Modelo cadastrado pelo responsável técnico',200),sheet:equipment,guidance:reportLayout?.guidance||[]}}};}
Deno.serve(async req=>{
 const origin=req.headers.get('origin')||'',headers={'Access-Control-Allow-Origin':origins.includes(origin)?origin:'null','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Vary':'Origin','Cache-Control':'no-store'};
 const respond=(x:unknown,status=200)=>Response.json(x,{status,headers});
 if(req.method==='OPTIONS')return new Response(null,{status:204,headers});if(req.method!=='POST')return respond({error:'Método inválido.'},405);if(origin&&!origins.includes(origin))return respond({error:'Origem não permitida.'},403);
 try{
  const {value:b,n}=await body(req);
  if(b.action==='companies'){const rows=await checked(admin.from('ppl_companies').select('id,slug,name,logo_data,brand_version,status').order('name').limit(500));return respond({rows:rows.map((c:any)=>({...brand(c),status:c.status}))});}
  if(b.action==='company-context'){const c=await company(b.companyId,b.slug);if(c.status!=='ready')throw new RequestError('Serviços da empresa em preparação.',409);const models=await templates(c),employees=await checked(admin.from('ppl_employees').select('id,name,employee_number,job_title').eq('company_id',c.id).eq('active',true).order('name').limit(5000));return respond({company:brand(c),models,employees});}
  if(b.action==='request'){
   const c=await company(b.companyId);if(!['Mensagem','Solicitação','Reclamação','Ajuste'].includes(b.category))throw new RequestError('Tipo de mensagem inválido.');const sender=text(b.sender),message=text(b.message,10000);if(!await checked(admin.rpc('ppl_reserve_intake',{n})))throw new RequestError('Envio indisponível. Tente novamente.',429);const row=await checked(admin.from('ppl_requests').insert({company_id:c.id,category:b.category,sender,message}).select('id').single());return respond({ok:true,id:row.id});
  }
  if(b.action==='submit'){
   const c=await company(b.record?.company?.id);const legacy=!b.record?.company;if(legacy&&c.slug!=='ppl')throw new RequestError('Identificação da empresa obrigatória.');
   const approved=await templates(c),matching=approved.find((m:any)=>m.snapshot.id===b.record?.model?.id&&m.snapshot.version===b.record?.model?.version);if(!matching)throw new RequestError('Modelo não cadastrado para esta empresa.');const r=normalizeRecord(b.record,approved.map((m:any)=>m.snapshot));
   if(!legacy){const v=await checked(admin.from('ppl_brand_versions').select('snapshot').eq('company_id',c.id).eq('version',r.company.version).maybeSingle());if(!v||canonical(v.snapshot)!==canonical(r.company))throw new RequestError('Identidade da empresa não reconhecida. Atualize o cadastro offline.');if(!uuid(r.staff?.id))throw new RequestError('Selecione um funcionário cadastrado.');const staff=await checked(admin.from('ppl_employees').select('*').eq('id',r.staff.id).eq('company_id',c.id).maybeSingle());if(!staff||r.fields.inspector!==staff.name||r.fields.employee!==staff.employee_number||r.fields.functionName!==staff.job_title)throw new RequestError('Funcionário não corresponde ao cadastro da empresa.');if(r.model.reportLayout?.type==='excel-original'){for(const field of r.model.identifiers.filter((f:any)=>f.type==='staff')){const employeeId=r.fields[field.name+'_id'];if(!uuid(employeeId))throw new RequestError('Selecione o inspetor cadastrado.');const employee=await checked(admin.from('ppl_employees').select('*').eq('id',employeeId).eq('company_id',c.id).maybeSingle());if(!employee||r.fields[field.name]!==employee.name||field.relatedEmployee&&r.fields[field.relatedEmployee]!==employee.employee_number)throw new RequestError('Inspetor não corresponde ao cadastro da empresa.');}}if(r.kind!==matching.kind)throw new RequestError('Tipo de documento inválido.');if(r.model.reportLayout?.variant==='vale-scaffold-1a'){const inspectorId=r.fields.v_scaffoldInspector_id;if(!uuid(inspectorId))throw new RequestError('Selecione o inspetor de andaimes cadastrado.');const inspector=await checked(admin.from('ppl_employees').select('*').eq('id',inspectorId).eq('company_id',c.id).maybeSingle());if(!inspector||r.fields.v_scaffoldInspector!==inspector.name||r.fields.v_scaffoldEmployee!==inspector.employee_number)throw new RequestError('Inspetor de andaimes não corresponde ao cadastro da empresa.');}}
   let pdf:Uint8Array|null=null;if(b.pdf!==undefined){if(typeof b.pdf!=='string'||b.pdf.length>15000000||!/^JVBER[A-Za-z0-9+/]+={0,2}$/.test(b.pdf))throw new RequestError('PDF inválido.');pdf=Uint8Array.from(atob(b.pdf),(x:string)=>x.charCodeAt(0));if(new TextDecoder().decode(pdf.slice(0,5))!=='%PDF-')throw new RequestError('PDF inválido.');}
   if(!await checked(admin.rpc('ppl_reserve_intake',{n})))throw new RequestError('Recebimento pausado ou limite diário atingido.',429);const digest=await hash(new TextEncoder().encode(canonical(r)));
   let row=await checked(admin.from('ppl_inspections').select('company_id,content_hash,pdf_hash,pdf_path,received_at').eq('key',r.key).maybeSingle());if(row&&(row.company_id!==c.id||row.content_hash!==digest))throw new RequestError('Conflito de empresa ou revisão.',409);
   if(!row){const insert=await admin.from('ppl_inspections').insert({key:r.key,id:r.id,revision:r.revision,company_id:c.id,record_kind:legacy?'checklist':matching.kind,content_hash:digest,pdf_hash:'',unit:r.fields.unit||'',team:r.fields.team||'',payload:r}).select('company_id,content_hash,pdf_hash,pdf_path,received_at').single();if(insert.error){row=await checked(admin.from('ppl_inspections').select('company_id,content_hash,pdf_hash,pdf_path,received_at').eq('key',r.key).maybeSingle());if(!row||row.company_id!==c.id||row.content_hash!==digest)throw new RequestError('Conflito de revisão ou falha ao preservar.',409);}else row=insert.data;}
   if(pdf&&!row.pdf_hash){const pdfHash=await hash(pdf),path=c.id+'/'+r.id+'/'+r.revision+'-'+digest+'-'+pdfHash+'.pdf';const upload=await admin.storage.from('ppl-private').upload(path,pdf,{contentType:'application/pdf',upsert:false});if(upload.error&&!['409','Duplicate'].includes(String(upload.error.statusCode))&&!String(upload.error.message).includes('already exists'))throw new RequestError('Inspeção recebida. PDF ainda pendente.',503);const attached=await checked(admin.from('ppl_inspections').update({pdf_hash:pdfHash,pdf_path:path}).eq('key',r.key).eq('company_id',c.id).eq('content_hash',digest).eq('pdf_hash','').select('company_id,content_hash,pdf_hash,pdf_path,received_at').maybeSingle());row=attached||await checked(admin.from('ppl_inspections').select('company_id,content_hash,pdf_hash,pdf_path,received_at').eq('key',r.key).maybeSingle());}
   return respond({key:r.key,received_at:row.received_at,pdf_ready:!!row.pdf_hash});
  }
  const authorization=req.headers.get('authorization')||'';if(!authorization.startsWith('Bearer '))throw new RequestError('Faça login.',401);const auth=await admin.auth.getUser(authorization.slice(7));if(auth.error||!auth.data.user)throw new RequestError('Sessão inválida.',401);
  const profile=await checked(admin.from('ppl_access').select('*').eq('user_id',auth.data.user.id).maybeSingle());if(!profile?.active)throw new RequestError('Acesso não autorizado ou suspenso.',403);
  const owner=profile.role==='owner',memberships=await checked(admin.from('ppl_company_access').select('*').eq('user_id',profile.user_id).eq('active',true));
  const selected=b.companyId?await company(b.companyId):await company();const member=memberships.find((m:any)=>m.company_id===selected.id);if(!owner&&!member)throw new RequestError('Você não possui acesso a esta empresa.',403);
  const scoped=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:authorization}},auth:{persistSession:false,autoRefreshToken:false}});
  if(b.action==='session')return respond({profile,memberships,company:brand(selected)});
  if(b.action==='list'||b.action==='owner-records'){
   if(b.action==='owner-records'&&!owner)throw new RequestError('Exclusivo do proprietário.',403);const offset=Number(b.offset||0);if(!Number.isInteger(offset)||offset<0)throw new RequestError('Página inválida.');let q=scoped.from('ppl_inspections').select('key,payload,company_id,record_kind,pdf_hash,received_at,archived_at');if(b.action==='list'||b.companyId)q=q.eq('company_id',selected.id);if(!(owner&&b.includeArchived===true))q=q.is('archived_at',null);const rows=await checked(q.order('received_at').order('key').range(offset,offset+49));return respond({rows:rows.map((row:any)=>{const r=structuredClone(row.payload);r.signature=null;r.workerPhoto=null;r.answers?.forEach((a:any)=>a.photos=[]);const {pdf_hash,...visible}=row;return {...visible,pdf_ready:!!pdf_hash,payload:r};})});
  }
  if(['pdf','events','event'].includes(b.action)){
   const row=await checked(scoped.from('ppl_inspections').select('key,id,revision,company_id,unit,team,content_hash,pdf_hash,pdf_path').eq('key',String(b.key)).maybeSingle());if(!row||(!owner&&row.company_id!==selected.id))throw new RequestError('Registro fora do seu acesso.',403);
   if(b.action==='pdf'){if(!row.pdf_hash)throw new RequestError('PDF pendente de envio.',409);const file=await checked(admin.storage.from('ppl-private').download(row.pdf_path||`${row.id}/${row.revision}-${row.content_hash}-${row.pdf_hash}.pdf`));return new Response(file,{headers:{...headers,'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="PR-${row.id}-r${row.revision}.pdf"`}});}
   if(b.action==='events')return respond({rows:await checked(scoped.from('ppl_events').select('*').eq('inspection_key',row.key).order('created_at'))});if(!['Aberto','Em acompanhamento','Encaminhado para avaliação técnica'].includes(b.state))throw new RequestError('Situação inválida.');await checked(admin.from('ppl_events').insert({inspection_key:row.key,actor_id:profile.user_id,actor_name:profile.name,state:b.state,note:text(b.note,10000)}));return respond({ok:true});
  }
  if(!owner)throw new RequestError('Operação exclusiva do proprietário.',403);
  if(b.action==='owner-companies'||b.action==='company-list-owner')return respond({rows:await checked(admin.from('ppl_companies').select('*').order('name'))});
  if(b.action==='company-create'){const name=text(b.name),logoData=logo(b.logoData),slug=name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)+'-'+crypto.randomUUID().slice(0,8);const c=await checked(admin.rpc('ppl_register_company',{p_name:name,p_slug:slug,p_logo:logoData}));return respond({company:brand(c),ok:true});}
  if(b.action==='company-release'){const c=await company(b.companyId),items=await templates(c);const staff=await checked(admin.from('ppl_employees').select('id').eq('company_id',c.id).eq('active',true).limit(1));if(!c.logo_data||!items.some((x:any)=>x.active)||!staff.length)throw new RequestError('Cadastre logo, funcionários e ao menos um modelo antes de liberar.');await checked(admin.from('ppl_companies').update({status:'ready'}).eq('id',c.id));return respond({ok:true});}
  if(b.action==='employees'){return respond({rows:await checked(admin.from('ppl_employees').select('*').eq('company_id',selected.id).order('name'))});}
  if(b.action==='employee-create'){const row=await checked(admin.from('ppl_employees').insert({company_id:selected.id,name:text(b.name),employee_number:text(b.employeeNumber,80),job_title:text(b.jobTitle)}).select('*').single());return respond({ok:true,employee:row});}
  if(b.action==='models')return respond({rows:await templates(selected)});
  if(b.action==='model-create'){const m=templateInput(b);await checked(admin.from('ppl_company_models').insert({company_id:selected.id,model_id:m.snapshot.id,version:m.snapshot.version,kind:m.kind,snapshot:m.snapshot}));return respond({ok:true,model:m});}
  if(b.action==='requests'){let q=admin.from('ppl_requests').select('*');if(b.companyId)q=q.eq('company_id',selected.id);return respond({rows:await checked(q.order('created_at',{ascending:false}).limit(500))});}
  if(b.action==='request-state'){if(!uuid(b.id)||!['Aberta','Em atendimento','Concluída'].includes(b.state))throw new RequestError('Solicitação inválida.');await checked(admin.from('ppl_requests').update({state:b.state,seen:true}).eq('id',b.id));return respond({ok:true});}
  if(b.action==='managers')return respond({rows:await checked(admin.from('ppl_access').select('*').eq('role','manager').order('name')),memberships:await checked(admin.from('ppl_company_access').select('*'))});
  if(b.action==='create-manager'){
   const input=managerInput(b.scopeMode==='company'?{...b,scopes:[{unit:'Toda a empresa',team:'Todas as equipes'}]}:b);const title=text(b.accessTitle||'Gestor');if(!['Gestor','Preposto','Técnico de Segurança do Trabalho','Técnico de Meio Ambiente'].includes(title))throw new RequestError('Perfil de acesso inválido.');const created=await admin.auth.admin.createUser({email:input.email,password:input.password,email_confirm:true});if(created.error||!created.data.user)throw new RequestError('Não foi possível criar o login. Confira se o e-mail já existe.');const id=created.data.user.id;
   try{await checked(admin.from('ppl_access').insert({user_id:id,name:input.name,role:'manager',active:false}));await checked(admin.from('ppl_company_access').insert({user_id:id,company_id:selected.id,access_title:title,scope_mode:b.scopeMode==='company'?'company':'teams'}));if(b.scopeMode!=='company')await checked(admin.from('ppl_scopes').insert(input.scopes.map((s:any)=>({...s,user_id:id,company_id:selected.id}))));await checked(admin.from('ppl_access').update({active:true}).eq('user_id',id));}catch(error){await admin.auth.admin.deleteUser(id);throw error;}return respond({ok:true});
  }
  if(b.action==='set-manager-active'){if(typeof b.active!=='boolean')throw new RequestError('Situação inválida.');const rows=await checked(admin.from('ppl_access').update({active:b.active}).eq('user_id',String(b.user_id)).eq('role','manager').select('user_id'));if(rows.length!==1)throw new RequestError('Gestor não encontrado.');return respond({ok:true});}
  throw new RequestError('Operação desconhecida.');
 }catch(error){return respond({error:error instanceof RequestError?error.message:'Serviço indisponível. Registros locais preservados.'},error instanceof RequestError?error.status:503);}
});
