window.PRArchive=(()=>{
 const digest=async bytes=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');
 function base64(bytes){let value='';for(let i=0;i<bytes.length;i+=32768)value+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(value);}
 function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
 async function history(companyId,entryId){const rows=[];let afterId=0;for(;;){const data=await PR.call('management-history',{companyId,entryId,afterId},true);rows.push(...data.rows);if(data.rows.length<100)break;const next=Number(data.rows.at(-1).id);if(!Number.isSafeInteger(next)||next<=afterId)throw Error('Histórico não pôde ser paginado com segurança.');afterId=next;}return rows;}
 async function verifiedFile(companyId,entryId,file){const blob=await PR.call('management-file-get',{companyId,entryId,fileId:file.id},true,true),bytes=new Uint8Array(await blob.arrayBuffer()),sha256=await digest(bytes);if(file.sha256&&sha256!==file.sha256)throw Error('O arquivo recebido difere do hash registrado. Download interrompido.');return {blob,bytes,sha256};}
 async function dossier(company,entry,files){const selected=files.filter(f=>f.entry_id===entry.id);if(selected.reduce((sum,f)=>sum+f.size,0)>33554432)throw Error('Dossiê acima de 32 MB. Baixe os arquivos individualmente e use o backup administrativo para a cópia completa.');const attachments=[];for(const file of selected){const {bytes,sha256}=await verifiedFile(company.id,entry.id,file);attachments.push({...file,sha256,hashRegistered:!!file.sha256,base64:base64(bytes)});}const events=await history(company.id,entry.id);return {format:'prs-document-dossier',schema:1,exportedAt:new Date().toISOString(),company,entry,history:events,files:attachments,notice:'Cópia de preservação. Hash verifica os bytes; não é assinatura digital. Guarde em local protegido.'};}
 return {digest,base64,download,history,verifiedFile,dossier};
})();
