/* Company-scoped authenticated management. No records stored in localStorage. */
window.PRManagementModules=(()=>{
 const E=x=>PR.escape(x),programs=['PGR','PCMSO','PPR','PCA','PAE','LIP','LTCAT'];
 const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Fortaleza',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const dateLabel=x=>x?x.split('-').reverse().join('/'):'—';
 const input=(name,label,type='text',value='',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${E(value)}" ${extra}></label>`;
 const select=(name,label,options,value='')=>`<label>${label}<select name="${name}">${options.map(x=>`<option ${x===value?'selected':''}>${E(x)}</option>`).join('')}</select></label>`;
 const metric=(n,label)=>`<article class="gm-metric"><strong>${n}</strong><span>${label}</span></article>`;
 const pill=(done,label)=>`<span class="gm-pill ${done?'done':'pending'}">${E(label)}</span>`;
 function aggregate(rows){const groups=new Map();for(const r of rows){const p=r.payload,key=p.type;if(!groups.has(key))groups.set(key,{type:key,sessions:0,people:new Set(),hours:0});const g=groups.get(key);if(p.status==='Realizado'){g.sessions++;for(const s of p.participants)g.people.add(s.id);g.hours+=p.hours*p.participants.length;}}return [...groups.values()].sort((a,b)=>a.type.localeCompare(b.type,'pt-BR'));}
 function actionState(p,day=today()){return p.status==='Realizado'?'Realizado':p.date<day?'Atrasado':'Pendente';}
 function monthDays(month){const [y,m]=month.split('-').map(Number),first=new Date(y,m-1,1),count=new Date(y,m,0).getDate();return {offset:(first.getDay()+6)%7,count};}
 function create({host,company,employees}){
  let rows=[],files=[],scopes=null,tab='attendance',epoch=0,alive=true,edit=null,draftId=crypto.randomUUID();
  const filters={start:'',end:'',type:'Todos',search:'',month:today().slice(0,7),program:'Todos',state:'Todos',unit:'Todas',team:'Todas'};
  const notify=message=>{if(alive){const el=host.querySelector('#gm-status');if(el)el.textContent=message;}};
  async function load(){const expected=++epoch,all=[],attachments=[];let offset=0,answer;do{answer=await PR.call('management-list',{companyId:company.id,offset},true);if(!alive||expected!==epoch)return;all.push(...answer.rows);attachments.push(...answer.files);offset+=100;}while(answer.rows.length===100);rows=all;files=attachments;scopes=answer.scopes;return true;}
  async function open(next){tab=next;edit=null;host.innerHTML='<section class="platform-box"><p role="status">Carregando área de gestão…</p></section>';try{if(await load())render();}catch(error){if(alive)host.innerHTML=`<section class="platform-box"><h2>Área de gestão em preparação</h2><p>Os novos módulos dependem da ativação no banco central. Nenhum cadastro foi salvo.</p><p role="alert">${E(error.message)}</p><button id="gm-retry">Tentar novamente</button></section>`;host.querySelector('#gm-retry')?.addEventListener('click',()=>open(tab));}}
  const scopeFields=(r={})=>scopes?.length?`<label>Unidade / equipe autorizada<select name="scope">${scopes.map((s,i)=>`<option value="${i}" ${s.unit===r?.unit&&s.team===r?.team?'selected':''}>${E(s.unit)} / ${E(s.team)}</option>`).join('')}</select></label>`:input('unit','Unidade','text',r?.unit||'','maxlength="150"')+input('team','Equipe','text',r?.team||'','maxlength="150"');
  function beginForm(title,inner,r){return `<section class="platform-box"><h2>${title}</h2><form id="gm-form"><div class="platform-grid">${inner}${scopeFields(r)}</div><label>Anexar documento / evidência (opcional, até 8 MB)<input name="attachment" type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.xlsx,.xls,.docx,.doc"></label><div class="gm-buttons"><button type="submit">${r?'Salvar alteração':'Salvar no sistema'}</button>${r?'<button type="button" id="gm-cancel">Cancelar edição</button>':''}</div></form></section>`;}
  function filtered(kind){return rows.filter(r=>r.kind===kind&&(filters.unit==='Todas'||r.unit===filters.unit)&&(filters.team==='Todas'||r.team===filters.team)&&(!filters.start||(r.payload.date||'')>=filters.start)&&(!filters.end||(r.payload.date||'')<=filters.end)&&(filters.type==='Todos'||r.payload.type===filters.type)&&(filters.program==='Todos'||r.payload.program===filters.program)&&(filters.state==='Todos'||actionState(r.payload)===filters.state)&&JSON.stringify(r.payload).toLocaleLowerCase('pt-BR').includes(filters.search.toLocaleLowerCase('pt-BR')));}
  function filterBar(kind){const training=kind==='training';return `<section class="platform-box"><h2>Filtros</h2><form id="gm-filters"><div class="platform-grid">${input('start','Data inicial','date',filters.start)}${input('end','Data final','date',filters.end)}${training?select('type','Treinamento',['Todos',...new Set(rows.filter(r=>r.kind==='training').map(r=>r.payload.type))],filters.type):select('program','Programa',['Todos',...programs],filters.program)+select('state','Situação',['Todos','Realizado','Pendente','Atrasado'],filters.state)}${select('unit','Unidade',['Todas',...new Set(rows.map(r=>r.unit).filter(Boolean))],filters.unit)}${select('team','Equipe',['Todas',...new Set(rows.map(r=>r.team).filter(Boolean))],filters.team)}${input('search','Buscar participante, título ou responsável','search',filters.search)}</div><button>Aplicar filtros</button><button type="button" id="gm-clear">Limpar filtros</button></form></section>`;}
  const attachmentList=r=>`<div class="gm-files">${files.filter(f=>f.entry_id===r.id).map(f=>`<button data-file="${E(f.id)}" data-entry="${E(r.id)}">Baixar ${E(f.name)}</button>`).join('')}<label>Adicionar evidência<input type="file" data-upload="${E(r.id)}" accept=".pdf,.png,.jpg,.jpeg,.webp,.xlsx,.xls,.docx,.doc"></label></div>`;
  function trainingForm(){const r=edit,p=r?.payload||{},ids=new Set(p.participants?.map(s=>s.id)||[]);return beginForm(r?'Editar treinamento':'Nova lista de frequência',input('title','Título / assunto','text',p.title||'','required maxlength="250"')+input('date','Data','date',p.date||today(),'required')+input('type','Tipo de treinamento','text',p.type||'','required list="gm-types" maxlength="160"')+`<datalist id="gm-types">${[...new Set(['Integração','DDS','Treinamento inicial','Reciclagem','Simulado',...rows.filter(r=>r.kind==='training').map(r=>r.payload.type)])].map(t=>`<option value="${E(t)}">`).join('')}</datalist>`+input('instructor','Instrutor / responsável','text',p.instructor||'','required maxlength="160"')+input('hours','Carga horária (horas)','number',p.hours||'','required min="0.01" max="1000" step="0.01"')+input('validUntil','Validade informada (opcional)','date',p.validUntil||'')+select('status','Situação',['Planejado','Realizado'],p.status||'Planejado')+`<fieldset class="gm-staff"><legend>Colaboradores cadastrados</legend><label>Buscar colaborador<input id="gm-staff-search" type="search" placeholder="Nome, matrícula ou função"></label><div class="gm-buttons"><button type="button" id="gm-select-all">Selecionar todos</button><button type="button" id="gm-deselect-all">Desmarcar todos</button></div><p class="platform-note">Com uma busca, os botões afetam apenas os colaboradores encontrados.</p><p><b id="gm-selected" aria-live="polite">${ids.size}</b> selecionados</p><div class="gm-staff-list">${employees.map(s=>`<label data-staff-label="${E(`${s.name} ${s.employee_number} ${s.job_title}`.toLocaleLowerCase('pt-BR'))}"><input name="participantIds" type="checkbox" value="${E(s.id)}" ${ids.has(s.id)?'checked':''}><span>${E(s.name)}<small>Matrícula ${E(s.employee_number)} · ${E(s.job_title)}</small></span></label>`).join('')||'<p>Nenhum colaborador cadastrado. O proprietário deve cadastrar o efetivo da empresa.</p>'}</div></fieldset>`,r);}
  function trainings(matrix){const visible=filtered('training'),done=visible.filter(r=>r.payload.status==='Realizado'),people=new Set(done.flatMap(r=>r.payload.participants.map(s=>s.id))),groups=aggregate(visible),maximum=Math.max(1,...groups.map(g=>g.people.size));return `${matrix?filterBar('training'):trainingForm()+`<section class="platform-box gm-notice"><strong>Modelo de frequência aguardando seu PDF</strong><p>É possível cadastrar o treinamento e selecionar os participantes. A emissão da lista com o mesmo layout do documento será habilitada após receber e mapear o modelo.</p></section>`}<div class="gm-metrics">${metric(done.length,'Treinamentos realizados')}${metric(people.size,'Colaboradores distintos treinados')}${metric(visible.filter(r=>r.payload.status==='Planejado').length,'Treinamentos planejados')}${metric(done.reduce((s,r)=>s+r.payload.hours*r.payload.participants.length,0).toLocaleString('pt-BR'),'Horas × participantes')}</div>${matrix?`<section class="platform-box"><h2>Participantes por tipo de treinamento</h2><p class="platform-note">Pessoas distintas dentro do período e dos filtros. Não representa cobertura do efetivo nem comprovação de habilitação.</p>${groups.map(g=>`<div class="gm-bar"><span>${E(g.type)}</span><div><i style="width:${g.people.size/maximum*100}%"></i></div><b>${g.people.size}</b></div>`).join('')||'<p>Nenhum treinamento no período.</p>'}</section>${monthlyChart(done)}${matrixTable(done)}`:''}<section class="platform-box"><h2>${matrix?'Treinamentos consultados':'Listas de frequência cadastradas'}</h2>${visible.sort((a,b)=>b.payload.date.localeCompare(a.payload.date)).map(r=>`<article class="platform-card"><h3>${E(r.payload.title)}</h3><p>${dateLabel(r.payload.date)} · ${E(r.payload.type)} · ${r.payload.hours} h · Instrutor: ${E(r.payload.instructor)}</p>${pill(r.payload.status==='Realizado',r.payload.status)}<p>${E(r.unit)} / ${E(r.team)} · ${r.payload.participants.length} participantes</p><details><summary>Ver participantes</summary><ul>${r.payload.participants.map(s=>`<li>${E(s.name)} · ${E(s.employee_number)} · ${E(s.job_title)}</li>`).join('')}</ul></details><button data-edit="${E(r.id)}">Editar cadastro</button>${attachmentList(r)}</article>`).join('')||'<p>Nenhum registro encontrado.</p>'}</section>`;}
  function monthlyChart(done){const counts=new Map();for(const r of done){const month=r.payload.date.slice(0,7);counts.set(month,(counts.get(month)||0)+1);}const max=Math.max(1,...counts.values());return `<section class="platform-box"><h2>Treinamentos realizados por mês</h2>${[...counts].sort().map(([m,n])=>`<div class="gm-bar"><span>${m.split('-').reverse().join('/')}</span><div><i style="width:${n/max*100}%"></i></div><b>${n}</b></div>`).join('')||'<p>Nenhum treinamento realizado.</p>'}</section>`;}
  function matrixTable(done){const types=[...new Set(done.map(r=>r.payload.type))].sort(),persons=new Map();for(const r of done)for(const s of r.payload.participants){if(!persons.has(s.id))persons.set(s.id,{staff:s,cells:{}});const cell=persons.get(s.id).cells,previous=cell[r.payload.type];if(!previous||previous.date<r.payload.date)cell[r.payload.type]=r.payload;}return `<section class="platform-box"><h2>Matriz por colaborador</h2><div class="table-scroll"><table class="platform-table"><thead><tr><th>Colaborador</th>${types.map(t=>`<th>${E(t)}</th>`).join('')}</tr></thead><tbody>${[...persons.values()].map(({staff,cells})=>`<tr><th>${E(staff.name)}<small>${E(staff.job_title)}</small></th>${types.map(t=>{const p=cells[t];return `<td>${p?dateLabel(p.date)+(p.validUntil?'<br>'+pill(p.validUntil>=today(),p.validUntil<today()?'Validade vencida':'Validade: '+dateLabel(p.validUntil)):'<small>Validade não informada</small>'):'—'}</td>`;}).join('')}</tr>`).join('')||'<tr><td>Nenhum participante no período.</td></tr>'}</tbody></table></div></section>`;}
  function legal(){const r=edit,p=r?.payload||{},kind=r?.kind||'legal-action',visible=filtered('legal-action'),done=visible.filter(r=>r.payload.status==='Realizado').length,pending=visible.length-done,late=visible.filter(r=>actionState(r.payload)==='Atrasado').length;return filterBar('legal-action')+`<div class="gm-metrics">${metric(visible.length,'Ações cadastradas')}${metric(done,'Realizadas')}${metric(pending,'Pendentes (inclui atrasadas)')}${metric(late,'Atrasadas')}</div><section class="platform-box"><h2>Execução das ações</h2><div class="gm-progress" aria-label="${done} realizadas de ${visible.length}"><span style="width:${visible.length?done/visible.length*100:0}%"></span></div><p>${pill(true,done+' realizadas')} ${pill(false,pending+' pendentes')}</p></section>${calendar(visible)}${beginForm(r?'Editar cadastro':'Cadastrar documento ou ação anual',`<label>Cadastro<select name="kind"><option value="legal-action" ${kind==='legal-action'?'selected':''}>Ação do programa</option><option value="legal-document" ${kind==='legal-document'?'selected':''}>Documento legal</option></select></label>`+select('program','Programa',programs,p.program)+input('title','Título / descrição','text',p.title||'','required maxlength="250"')+input('date','Data prevista da ação / emissão do documento','date',p.date||today(),'required')+input('validUntil','Próxima revisão prevista do documento (opcional)','date',p.validUntil||'')+input('responsible','Responsável pela ação','text',p.responsible||'','maxlength="160"')+select('status','Situação da ação',['Pendente','Realizado'],p.status)+input('completedDate','Data da realização','date',p.completedDate||'')+`<label>Observações<textarea name="notes" maxlength="10000">${E(p.notes||'')}</textarea></label>`,r)}<section class="platform-box"><h2>Ações do programa</h2>${visible.sort((a,b)=>a.payload.date.localeCompare(b.payload.date)).map(r=>legalCard(r)).join('')||'<p>Nenhuma ação nos filtros selecionados.</p>'}</section><section class="platform-box"><h2>Documentos legais</h2><p class="platform-note">Datas, aplicabilidade e ações são cadastradas pelo responsável. Não são criados prazos legais automaticamente.</p>${programs.map(program=>`<details><summary>${program} · ${rows.filter(r=>r.kind==='legal-document'&&r.payload.program===program).length} documentos</summary>${rows.filter(r=>r.kind==='legal-document'&&r.payload.program===program).map(r=>legalCard(r)).join('')||'<p>Documento ainda não cadastrado.</p>'}</details>`).join('')}</section>`;}
  function legalCard(r){const p=r.payload;return `<article class="platform-card"><h3>${E(p.program)} · ${E(p.title)}</h3><p>${dateLabel(p.date)} · ${E(r.unit)} / ${E(r.team)}</p>${r.kind==='legal-action'?pill(p.status==='Realizado',actionState(p))+`<p>Responsável: ${E(p.responsible)}${p.completedDate?' · Realizado em '+dateLabel(p.completedDate):''}</p>`:`<p>Próxima revisão prevista: ${dateLabel(p.validUntil)}</p>`}<p class="gm-notes">${E(p.notes)}</p><button data-edit="${E(r.id)}">Editar cadastro</button>${attachmentList(r)}</article>`;}
  function calendar(visible){const {offset,count}=monthDays(filters.month),events=visible.filter(r=>r.payload.date.startsWith(filters.month));return `<section class="platform-box"><h2>Calendário de ações</h2><label>Mês<input id="gm-month" type="month" value="${filters.month}" required></label><p class="platform-note">Verde: realizada · Vermelho: pendente · Texto identifica ações atrasadas. Respeita os filtros acima.</p><div class="gm-calendar">${['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(d=>`<div class="gm-weekday">${d}</div>`).join('')}${'<div class="gm-empty"></div>'.repeat(offset)}${Array.from({length:count},(_,i)=>{const d=filters.month+'-'+String(i+1).padStart(2,'0');return `<div class="gm-day"><b>${i+1}</b>${events.filter(r=>r.payload.date===d).map(r=>`<button class="${r.payload.status==='Realizado'?'done':'pending'}" data-edit="${E(r.id)}">${E(r.payload.program)} · ${E(r.payload.title)}<small>${actionState(r.payload)}</small></button>`).join('')}</div>`;}).join('')}</div>${events.length?'':'<p>Nenhuma ação cadastrada neste mês.</p>'}</section>`;}
  function nrs(){const r=edit,p=r?.payload||{};return beginForm(r?'Editar NR':'Controle de NRs',input('number','Número da NR (ex.: NR-35)','text',p.number||'','required pattern="NR-[0-9]{1,2}"')+input('title','Título / assunto controlado','text',p.title||'','required maxlength="250"')+select('applicability','Aplicabilidade',['Em avaliação','Aplicável','Não aplicável'],p.applicability)+input('date','Data de revisão / avaliação (opcional)','date',p.date||'')+`<label>Requisitos avaliados / observações<textarea name="notes" maxlength="10000">${E(p.notes||'')}</textarea></label>`,r)+`<section class="platform-box"><h2>NRs cadastradas</h2><p class="platform-note">Repositório de documentos e avaliações da empresa. O cadastro não declara atendimento automático aos requisitos.</p>${rows.filter(r=>r.kind==='nr').sort((a,b)=>Number(a.payload.number.slice(3))-Number(b.payload.number.slice(3))).map(r=>`<article class="platform-card"><h3>${E(r.payload.number)} · ${E(r.payload.title)}</h3><p>${E(r.payload.applicability)} · Revisão: ${dateLabel(r.payload.date)}</p><p class="gm-notes">${E(r.payload.notes)}</p><button data-edit="${E(r.id)}">Editar cadastro</button>${attachmentList(r)}</article>`).join('')||'<p>Nenhuma NR cadastrada.</p>'}</section>`;}
  function render(){if(!alive)return;host.innerHTML='<p id="gm-status" role="status" aria-live="polite"></p>'+(tab==='attendance'?trainings(false):tab==='training'?trainings(true):tab==='legal'?legal():tab==='nrs'?nrs():'<section class="platform-box"><h2>Permissão de trabalho</h2><p>Aguardando o modelo que você enviará para reproduzir os campos e o PDF original.</p></section>');bind();}
  function bind(){
   const form=host.querySelector('#gm-form');if(form){form.onsubmit=save;host.querySelector('#gm-cancel')?.addEventListener('click',()=>{edit=null;render();});
    const search=host.querySelector('#gm-staff-search');if(search){const count=()=>host.querySelector('#gm-selected').textContent=form.querySelectorAll('[name=participantIds]:checked').length;const bulk=checked=>{host.querySelectorAll('[data-staff-label]').forEach(l=>{if(!l.hidden)l.querySelector('[name=participantIds]').checked=checked;});count();};host.querySelector('#gm-select-all').onclick=()=>bulk(true);host.querySelector('#gm-deselect-all').onclick=()=>bulk(false);search.oninput=()=>{const q=search.value.trim().toLocaleLowerCase('pt-BR');host.querySelectorAll('[data-staff-label]').forEach(l=>l.hidden=!l.dataset.staffLabel.includes(q));const filtered=!!q;host.querySelector('#gm-select-all').textContent=filtered?'Selecionar encontrados':'Selecionar todos';host.querySelector('#gm-deselect-all').textContent=filtered?'Desmarcar encontrados':'Desmarcar todos';};form.addEventListener('change',count);}
    if(tab==='legal'){const toggle=()=>{const action=form.elements.kind.value==='legal-action';for(const name of ['responsible','status','completedDate']){form.elements[name].closest('label').hidden=!action;form.elements[name].required=action&&(name==='responsible'||name==='completedDate'&&form.elements.status.value==='Realizado');}form.elements.validUntil.closest('label').hidden=action;};form.elements.kind.onchange=toggle;form.elements.status.onchange=toggle;toggle();}
   }
   const ff=host.querySelector('#gm-filters');if(ff){ff.onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(ff));if(f.start&&f.end&&f.start>f.end){notify('Data inicial não pode ser posterior à final.');return;}Object.assign(filters,f);render();};host.querySelector('#gm-clear').onclick=()=>{Object.assign(filters,{start:'',end:'',type:'Todos',search:'',program:'Todos',state:'Todos',unit:'Todas',team:'Todas'});render();};}
   host.querySelector('#gm-month')?.addEventListener('change',e=>{if(e.target.value){filters.month=e.target.value;render();}});
   host.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{edit=rows.find(r=>r.id===b.dataset.edit);if(edit.kind==='training')tab='attendance';render();host.querySelector('#gm-form')?.scrollIntoView({behavior:'smooth',block:'start'});});
   host.querySelectorAll('[data-file]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const blob=await PR.call('management-file-get',{companyId:company.id,entryId:b.dataset.entry,fileId:b.dataset.file},true,true);if(!alive)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=files.find(f=>f.id===b.dataset.file).name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);notify('Arquivo preparado para download.');}catch(e){notify(e.message);}finally{b.disabled=false;}});
   host.querySelectorAll('[data-upload]').forEach(el=>el.onchange=async()=>{const file=el.files[0];if(!file)return;el.disabled=true;try{await upload(el.dataset.upload,file);if(await load()){render();notify('Evidência guardada no sistema.');}}catch(e){notify('Não foi possível guardar o arquivo: '+e.message);}finally{el.disabled=false;}});
  }
  async function upload(entryId,file){if(file.size<=0||file.size>8388608)throw Error('Escolha um arquivo de até 8 MB.');const base64=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=()=>no(Error('Falha na leitura do arquivo.'));r.readAsDataURL(file);});await PR.call('management-file-put',{companyId:company.id,entryId,name:file.name,base64},true);}
  async function save(event){event.preventDefault();const form=event.currentTarget,button=form.querySelector('[type=submit]'),values=Object.fromEntries(new FormData(form)),kind=tab==='attendance'?'training':tab==='nrs'?'nr':values.kind,id=edit?.id||draftId,selectedScope=scopes?.length?scopes[Number(values.scope)]:{unit:values.unit||'',team:values.team||''},file=form.elements.attachment.files[0];if(file&&file.size>8388608){notify('Anexo excede 8 MB.');return;}
   const payload={...values,participantIds:new FormData(form).getAll('participantIds')};delete payload.attachment;button.disabled=true;notify('Salvando no servidor…');let saved=false;
   try{await PR.call('management-save',{companyId:company.id,id,kind,version:edit?.version,...selectedScope,payload},true);saved=true;let fileError='';if(file)try{await upload(id,file);}catch(e){fileError=' O cadastro foi salvo, mas o anexo não: '+e.message+' Use Adicionar evidência para tentar novamente.';}edit=null;draftId=crypto.randomUUID();if(await load()){render();notify('Cadastro salvo no sistema.'+fileError);}}
   catch(e){notify((saved?'Cadastro salvo, mas não foi possível atualizar a consulta. Use Atualizar registros. ':'Nenhum sucesso confirmado. Mantenha o formulário aberto e atualize a consulta antes de reenviar. ')+e.message);}finally{button.disabled=false;}
  }
  return {open,refresh:()=>open(tab),destroy(){alive=false;++epoch;rows=[];files=[];host.replaceChildren();}};
 }
 return {create,aggregate,actionState,monthDays};
})();
