(()=>{
let generation=0;
const escape=PR.escape;
function itemsFromText(raw){
 let source=String(raw||'').replace(/\r/g,'');const marker=source.search(/RELA[CÇ][AÃ]O DE ITENS DE VERIFICA[CÇ][AÃ]O/i);if(marker>=0)source=source.slice(marker);const lines=source.split('\n').map(x=>x.trim()).filter(Boolean);const numbered=[];let current=null;
 for(let line of lines){line=line.replace(/N[aã]o utilizar at[eé] regulariza[cç][aã]o/ig,'').trim();if(!line||/^(CONFORME|N[AÃ]O CONFORME|N[AÃ]O APLIC[AÁ]VEL|A[CÇ][AÃ]O REQUERIDA|INSTALA[CÇ][AÃ]O|OBSERVA[CÇ][OÕ]ES|RELA[CÇ][AÃ]O DE ITENS)/i.test(line))continue;const m=line.match(/^(\d{1,3})\s*[.)-]?\s+(.+)$/);if(m){if(current)numbered.push(current);current={number:Number(m[1]),text:m[2]};}else if(current&&!/^\d+$/.test(line))current.text+=' '+line;}
 if(current)numbered.push(current);if(numbered.length)return numbered.filter(x=>x.text.length>8).map(x=>x.text);
 const questions=source.match(/[^?]+\?/g)||[];return questions.map(x=>x.replace(/\s+/g,' ').trim()).filter(x=>x.length>10);
}
window.PR_PHOTO_ITEMS=itemsFromText;
function layoutControls(){return '<fieldset id="procedure-options" hidden><legend>Informações do procedimento original</legend><label>Título do procedimento<input name="procedureTitle" maxlength="250"></label><label>Código<input name="procedureCode" maxlength="80"></label><label>Revisão<input name="procedureRevision" maxlength="40"></label><label>Data da revisão<input name="procedureDate" type="date"></label><label>Título do anexo<input name="annexTitle" maxlength="200"></label><label>Seção dos itens<input name="sectionTitle" value="VERIFICAÇÃO" maxlength="80"></label><label>Orientações do formulário<textarea name="procedureGuidance" placeholder="Uma orientação por linha"></textarea></label><label>Ação requerida para Não Conforme<input name="nonconformingAction" maxlength="250" value="Não utilizar até regularização"></label><label>Quantidade total de linhas no formulário<input name="totalRows" type="number" min="1" max="80" value="22"></label><p>As linhas adicionais ficam vazias no PDF; não se tornam perguntas obrigatórias.</p></fieldset>';}
window.PR_INSTALL_PHOTO_IMPORT=function(form){
 const previous=form.querySelector('#photo-import');if(previous)return;let busy=false,angle=0,image=null,fileHash='',originalName='',read=false;
 const block=document.createElement('section');block.className='photo-import';block.id='photo-import';block.innerHTML='<h3>Transformar foto em checklist</h3><p>Escolha uma foto legível do formulário. A leitura acontece neste aparelho; revise o texto e os itens antes de salvar.</p><label>Foto do formulário<input id="model-photo" type="file" accept="image/png,image/jpeg,image/webp"></label><div class="photo-preview" hidden><canvas id="model-photo-preview"></canvas><div class="platform-nav"><button type="button" id="photo-rotate">Girar 90°</button><button type="button" id="photo-read">Ler informações da foto</button><button type="button" id="photo-cancel" hidden>Cancelar leitura</button></div></div><p id="photo-state" role="status" aria-live="polite"></p><label>Texto extraído — editável<textarea id="photo-text" placeholder="O texto reconhecido aparecerá aqui"></textarea></label><button type="button" id="photo-build">Transformar texto em itens para revisão</button><button type="button" id="load-vale-scaffold">Usar anexo de andaimes enviado</button><p id="photo-count" role="status"></p>';
 form.prepend(block);const items=form.elements.items.closest('label');const format=document.createElement('section');format.innerHTML='<label>Interface e PDF do modelo<select name="reportFormat"><option value="standard">Padrão da empresa</option><option value="procedure-table">Vale RAC 01 — andaimes (Anexo 1A)</option></select></label>'+layoutControls()+'<label class="review-choice"><input name="reviewedPhoto" type="checkbox"> Conferi as perguntas, campos e orientações com o documento de origem.</label>';items.before(format);
 const preview=block.querySelector('canvas'),state=block.querySelector('#photo-state'),text=block.querySelector('#photo-text');
 function draw(){const rotated=angle%180!==0,scale=Math.min(3,2200/Math.max(image.width,image.height));preview.width=Math.round((rotated?image.height:image.width)*scale);preview.height=Math.round((rotated?image.width:image.height)*scale);const c=preview.getContext('2d');c.translate(preview.width/2,preview.height/2);c.rotate(angle*Math.PI/180);c.drawImage(image,-image.width*scale/2,-image.height*scale/2,image.width*scale,image.height*scale);}
 function setBusy(value){busy=value;block.querySelector('#photo-read').disabled=value;block.querySelector('#photo-rotate').disabled=value;block.querySelector('#model-photo').disabled=value;block.querySelector('#photo-cancel').hidden=!value;form.querySelector('button[type="submit"],button:not([type])').disabled=value;}
 form.elements.reportFormat.onchange=()=>{form.querySelector('#procedure-options').hidden=form.elements.reportFormat.value!=='procedure-table';};
 block.querySelector('#model-photo').onchange=async e=>{generation++;angle=0;read=false;fileHash='';form.elements.reviewedPhoto.checked=false;const f=e.target.files[0];if(!f)return;try{if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>15000000)throw Error('Escolha uma foto PNG, JPEG ou WebP de até 15 MB.');originalName=f.name;image=await createImageBitmap(f);const digest=await crypto.subtle.digest('SHA-256',await f.arrayBuffer());fileHash=[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('');draw();block.querySelector('.photo-preview').hidden=false;state.textContent='Confira a orientação da foto antes de iniciar a leitura.';}catch(e){state.textContent=e.message;}};
 block.querySelector('#photo-rotate').onclick=()=>{if(busy||!image)return;angle=(angle+90)%360;draw();form.elements.reviewedPhoto.checked=false;};
 let worker=null;
 block.querySelector('#photo-cancel').onclick=()=>{generation++;worker?.terminate();worker=null;setBusy(false);state.textContent='Leitura cancelada. O formulário permanece disponível.';};
 block.querySelector('#photo-read').onclick=async()=>{if(busy||!image)return;const expected=++generation;setBusy(true);state.textContent='Preparando leitura em português…';let timeout,localWorker=null;
 try{if(!window.Tesseract)await new Promise((ok,no)=>{const script=document.createElement('script');script.src='vendor/ocr/tesseract.min.js';script.onload=ok;script.onerror=()=>no(Error('Não foi possível carregar o leitor. Conecte-se à internet e tente novamente.'));document.head.append(script);});
 const run=async()=>{localWorker=await Tesseract.createWorker('por',1,{workerPath:new URL('vendor/ocr/worker.min.js',location.href).href,corePath:new URL('vendor/ocr/core/',location.href).href,langPath:new URL('vendor/ocr/lang',location.href).href,workerBlobURL:false,logger:m=>{if(expected===generation&&m.status)state.textContent='Leitura da foto: '+Math.round((m.progress||0)*100)+'%';}});if(expected!==generation){await localWorker.terminate();localWorker=null;throw Error('Leitura cancelada.');}worker=localWorker;await localWorker.setParameters({tessedit_pageseg_mode:3,user_defined_dpi:'300'});return localWorker.recognize(preview.toDataURL('image/png'));};
 const result=await Promise.race([run(),new Promise((_,no)=>timeout=setTimeout(()=>no(Error('A leitura demorou. Tente uma foto mais próxima, nítida e alinhada.')),180000))]);if(expected!==generation)return;text.value=result.data.text||'';read=true;form.elements.reviewedPhoto.checked=false;state.textContent=result.data.confidence<75?'Leitura com baixa confiança. Confira cuidadosamente cada item; se necessário, use uma foto mais próxima ou o modelo do anexo já conferido.':'Texto extraído. Revise abaixo antes de montar os itens.';if(!text.value.trim())state.textContent='Nenhum texto legível foi reconhecido. Tente outra foto.';
 }catch(e){if(expected===generation)state.textContent=e.message;}finally{clearTimeout(timeout);await localWorker?.terminate();if(expected===generation){worker=null;setBusy(false);}}};
 block.querySelector('#photo-build').onclick=()=>{const extracted=itemsFromText(text.value);if(!extracted.length){state.textContent='Não identifiquei perguntas. Revise o texto e coloque uma pergunta por linha em Itens técnicos.';return;}form.elements.items.value=extracted.join('\n');form.elements.reviewedPhoto.checked=false;block.querySelector('#photo-count').textContent=extracted.length+' itens sugeridos. Confira a sequência com a foto.';const code=text.value.match(/PRO[- ]?\d{5,8}/i);if(code)form.elements.procedureCode.value=code[0].replace(' ','-');};
 block.querySelector('#load-vale-scaffold').onclick=()=>{const m=window.VALE_SCAFFOLD_MODEL,l=m.reportLayout;form.elements.kind.value='checklist';form.elements.title.value=m.title;form.elements.equipment.value=m.equipmentName;form.elements.formCode.value=m.source.form;form.elements.inspectionType.value=m.types[0];form.elements.items.value=m.items.map(i=>i.category+' | '+i.text).join('\n');form.elements.reportFormat.value='procedure-table';form.elements.procedureTitle.value=l.procedureTitle;form.elements.procedureCode.value=l.procedureCode;form.elements.procedureRevision.value=l.revision;form.elements.procedureDate.value='2026-07-01';form.elements.annexTitle.value=l.annexTitle;form.elements.sectionTitle.value=l.sectionTitle;form.elements.procedureGuidance.value=l.guidance.join('\n');form.elements.nonconformingAction.value=l.action;form.elements.totalRows.value=l.totalRows;form.elements.reviewedPhoto.checked=false;form.elements.reportFormat.onchange();block.querySelector('#photo-count').textContent='16 perguntas e seis linhas em branco. Confira o modelo do anexo antes de salvar.';};
 form.PRPhotoValues=()=>{const format=form.elements.reportFormat.value,photoPresent=!!fileHash;if((photoPresent||format==='procedure-table')&&!form.elements.reviewedPhoto.checked)throw Error('Confira o conteúdo com a foto e marque a revisão antes de salvar.');const provenance=photoPresent?{type:'photo',filename:originalName,sha256:fileHash,reviewed:true}:null;if(format!=='procedure-table')return {photoOrigin:provenance};const count=form.elements.items.value.split(/\r?\n/).filter(x=>x.trim()).length,rows=Number(form.elements.totalRows.value);if(rows<count||rows>80)throw Error('O número de linhas precisa acomodar todos os itens (máximo 80).');const l=VALE_SCAFFOLD_MODEL.reportLayout;return {photoOrigin:provenance,reportLayout:{...l,procedureTitle:form.elements.procedureTitle.value,procedureCode:form.elements.procedureCode.value,revision:form.elements.procedureRevision.value,revisionDate:form.elements.procedureDate.value.split('-').reverse().join('/'),annexTitle:form.elements.annexTitle.value,sectionTitle:form.elements.sectionTitle.value,totalRows:rows,action:form.elements.nonconformingAction.value,guidance:form.elements.procedureGuidance.value.split(/\r?\n/).filter(x=>x.trim()),reviewed:true}};};
};
})();