function procedureIdentifier(f){
 if(f.type==='staff'){const rows=window.PRContext?.employees||[];return '<label>'+esc(f.label)+'<select name="auxstaff-'+esc(f.name)+'" data-procedure-staff="'+esc(f.name)+'" required><option value="">Selecione o funcionário cadastrado</option>'+rows.map(s=>'<option value="'+esc(s.id)+'" '+(current.fields[f.name+'_id']===s.id?'selected':'')+'>'+esc(s.name)+'</option>').join('')+'</select></label>';}
 return '<label>'+esc(f.label)+'<input name="'+esc(f.name)+'" type="'+(f.type==='date'?'date':'text')+'" value="'+esc(current.fields[f.name]||'')+'" '+(f.type==='readonly'?'readonly class="staff-auto"':'')+' '+(f.required?'required':'')+'></label>';
}
function captureProcedureStaff(){if(nativeChecklist(current)){captureNativeStaff();return;}if(!current?.model.reportLayout)return;document.querySelectorAll('[data-procedure-staff]').forEach(select=>{const field=select.dataset.procedureStaff,person=PRContext.employees.find(s=>s.id===select.value);current.fields[field]=person?.name||'';current.fields[field+'_id']=person?.id||'';current.fields.v_scaffoldEmployee=person?.employee_number||'';const output=document.querySelector('[name="v_scaffoldEmployee"]');if(output)output.value=current.fields.v_scaffoldEmployee;});}
function decorateProcedureForm(r,draft){
 const layout=r.model.reportLayout;if(layout?.type!=='procedure-table')return;const form=document.querySelector('#form'),existing=[...form.querySelectorAll('article.item')];const header=document.createElement('section');header.className='panel procedure-original';header.innerHTML='<div class="procedure-source-heading"><h2>'+esc(layout.procedureTitle)+'</h2>'+(layout.sourceLogoData?'<img src="'+esc(layout.sourceLogoData)+'" alt="Vale — marca do documento de origem">':'<b>VALE</b>')+'</div><p>'+esc(layout.procedureCode)+', Rev.'+esc(layout.revision)+': '+esc(layout.revisionDate)+'</p><h3>'+esc(layout.annexTitle)+'</h3><div id="procedure-main-fields" class="procedure-head-grid"></div><div id="procedure-service-fields"></div><div id="procedure-inspector-fields" class="procedure-head-grid three"></div><div id="procedure-daily-fields" class="procedure-head-grid three"></div><div class="procedure-guidance"><strong>ORIENTAÇÕES:</strong>'+layout.guidance.map(x=>'<p>'+esc(x)+'</p>').join('')+'</div>';form.prepend(header);
 const move=(name,target,label)=>{const input=form.querySelector('[name="'+name+'"]'),host=input?.closest('label');if(host){if(label&&host.firstChild?.nodeType===3)host.firstChild.textContent=label;header.querySelector(target).append(host);}};
 move('v_department','#procedure-main-fields');const company=document.createElement('label');company.textContent='EMPRESA';const companyValue=document.createElement('input');companyValue.value=r.company?.name||'PPL Manutenção';companyValue.readOnly=true;company.append(companyValue);header.querySelector('#procedure-main-fields').append(company);move('belt','#procedure-main-fields','LOCAL/EQUIPAMENTO');move('date','#procedure-main-fields','DATA');move('v_service','#procedure-service-fields');move('auxstaff-v_scaffoldInspector','#procedure-inspector-fields');move('v_scaffoldEmployee','#procedure-inspector-fields');move('v_scaffoldDate','#procedure-inspector-fields','DATA');move('staffId','#procedure-daily-fields','NOME DO RESPONSÁVEL PELA VERIFICAÇÃO DIÁRIA (USUÁRIO)');move('employee','#procedure-daily-fields','MATRÍCULA');move('v_dailyDate','#procedure-daily-fields','DATA');
 header.querySelectorAll('input,select').forEach(input=>input.disabled=!draft);
 const pane=document.createElement('section');pane.className='panel procedure-original';pane.innerHTML='<h3>'+esc(layout.sectionTitle)+'</h3><p class="procedure-scroll-help">Marque uma resposta por item. No celular, deslize a tabela para visualizar todas as colunas.</p><div class="procedure-table-scroll"><table class="procedure-table"><thead><tr><th colspan="2">RELAÇÃO DE ITENS DE VERIFICAÇÃO</th><th>CONFORME</th><th>NÃO CONFORME</th><th>NÃO APLICÁVEL</th><th>AÇÃO REQUERIDA PARA NÃO CONFORME</th></tr></thead><tbody></tbody></table></div>';
 header.after(pane);const tbody=pane.querySelector('tbody'),evidence=document.createElement('details');evidence.className='panel procedure-evidence';evidence.innerHTML='<summary>Observações e evidências por item</summary>';pane.after(evidence);
 r.model.items.forEach((item,n)=>{const row=document.createElement('tr');row.innerHTML='<td>'+esc(item.sourceNumber||n+1)+'</td><td>'+esc(item.text)+'</td><td></td><td></td><td></td><td class="procedure-action">'+esc(item.action||layout.action)+'</td>';const choices=existing[n].querySelectorAll('.answer-cards label');choices.forEach((label,j)=>{label.className='procedure-choice';row.children[j+2].append(label);});tbody.append(row);existing[n].querySelector('.answer-group')?.remove();existing[n].querySelector('p')?.remove();existing[n].querySelector('small')?.remove();existing[n].querySelector('h3').textContent='Item '+(n+1)+' — observações e fotos';evidence.append(existing[n]);});
 for(let n=r.model.items.length;n<layout.totalRows;n++){const row=document.createElement('tr');row.className='procedure-blank';row.innerHTML='<td>'+(n+1)+'</td><td></td><td></td><td></td><td></td><td></td>';tbody.append(row);}
}
