async function makeProcedurePDF(r){
 const {PDFDocument,StandardFonts,rgb}=PDFLib,doc=await PDFDocument.create(),font=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold),layout=r.model.reportLayout;
 const ink=rgb(0,0,0),grey=rgb(.93,.93,.93),lineColor=rgb(.18,.18,.18),left=32,width=531,pageHeight=841.89;let page,y,pageNumber=0;const clean=x=>String(x??'').replace(/[\u2010-\u2015]/g,'-').replace(/[“”]/g,'"').replace(/[‘’]/g,"'").replace(/[^\u0020-\u007e\u00a0-\u00ff\n]/g,'?');
 function wrap(value,size,max,f=font){const rows=[];for(const paragraph of clean(value).split('\n')){let line='';for(const word of paragraph.split(/\s+/)){if(!word)continue;if(f.widthOfTextAtSize((line?line+' ':'')+word,size)>max&&line){rows.push(line);line='';}if(f.widthOfTextAtSize(word,size)>max){for(const c of word){if(f.widthOfTextAtSize(line+c,size)>max&&line){rows.push(line);line='';}line+=c;}}else line+=(line?' ':'')+word;}rows.push(line);}return rows;}
 function text(value,x,top,size=7,max=width,f=font){const lines=wrap(value,size,max,f);lines.forEach((line,i)=>page.drawText(line,{x,y:top-size-i*(size+1),size,font:f,color:ink}));return lines.length*(size+1);}
 function rect(x,top,w,h,fill){page.drawRectangle({x,y:top-h,width:w,height:h,borderColor:lineColor,borderWidth:.55,...(fill?{color:fill}:{})});}
 const companyLogo=r.company?.logoData?await (r.company.logoData.startsWith('data:image/jpeg;')?doc.embedJpg(r.company.logoData):doc.embedPng(r.company.logoData)):null;
 const issuerLogo=layout.sourceLogoData?await doc.embedPng(layout.sourceLogoData):null;
 function newPage(){page=doc.addPage([595.28,pageHeight]);pageNumber++;y=806;text(layout.procedureTitle,left,y,9.2,width-62,bold);if(issuerLogo){const sz=issuerLogo.scale(Math.min(54/issuerLogo.width,24/issuerLogo.height));page.drawImage(issuerLogo,{x:509,y:786,width:sz.width,height:sz.height});}else text(layout.issuer||'VALE',515,y,9,48,bold);page.drawLine({start:{x:left,y:786},end:{x:left+width,y:786},thickness:1,color:ink});text(layout.procedureCode+', Rev.'+layout.revision+': '+layout.revisionDate,left,780,7.2,width,bold);y=765;if(companyLogo){const sz=companyLogo.scale(Math.min(55/companyLogo.width,13/companyLogo.height));page.drawImage(companyLogo,{x:left,y:10,width:sz.width,height:sz.height});}text((r.company?.name||'PPL Manutenção')+' | ID '+r.id+' | r'+r.revision+' | página '+pageNumber,left+62,24,5.4,width-62);if(r.preview){text('DEMONSTRAÇÃO - SEM INSPEÇÃO REAL',left+135,38,7,370,bold);}}
 function heading(label,h=15){rect(left,y,width,h,grey);const s=7.3,lines=wrap(label,s,width-8,bold);const offset=Math.max(0,(h-lines.length*(s+1))/2);lines.forEach((line,i)=>page.drawText(line,{x:left+(width-bold.widthOfTextAtSize(line,s))/2,y:y-offset-s-i*(s+1),size:s,font:bold}));y-=h;}
 function cells(values,widths,height=21){let x=left;values.forEach(([label,value],n)=>{const w=widths[n];rect(x,y,w,height);const labels=wrap(label,6.0,w-6,bold);labels.forEach((line,j)=>text(line,x+3,y-2-j*7,6,w-6,bold));const used=labels.length*7+3;text(value,x+3,y-used,6.7,w-6);x+=w;});y-=height;}
 newPage();heading(layout.annexTitle,17);
 cells([['GERÊNCIA',r.fields.v_department],['EMPRESA',r.company?.name||'PPL Manutenção'],['LOCAL/EQUIPAMENTO',r.fields.belt],['DATA',r.fields.date]],[126,126,192,87]);
 cells([['SERVIÇO A SER REALIZADO:',r.fields.v_service]],[width],19);
 cells([['NOME INSPETOR DE ANDAIMES:',r.fields.v_scaffoldInspector],['MATRÍCULA',r.fields.v_scaffoldEmployee],['DATA',r.fields.v_scaffoldDate]],[280,125,126],20);
 cells([['NOME DO RESPONSÁVEL PELA VERIFICAÇÃO DIÁRIA (USUÁRIO)',r.fields.inspector],['MATRÍCULA',r.fields.employee],['DATA',r.fields.v_dailyDate||r.fields.date]],[280,125,126],25);
 const guidanceSize=6.2,guidanceLines=layout.guidance.flatMap(t=>wrap(t,guidanceSize,width-8,bold)),guidanceHeight=12+guidanceLines.length*(guidanceSize+1)+4;rect(left,y,width,guidanceHeight,grey);text('ORIENTAÇÕES:',left+4,y-3,guidanceSize,width-8,bold);guidanceLines.forEach((line,n)=>text(line,left+4,y-13-n*(guidanceSize+1),guidanceSize,width-8,bold));y-=guidanceHeight;
 const columns=[14,189,80,80,80,88];const headerLabels=['','RELAÇÃO DE ITENS DE VERIFICAÇÃO','CONFORME','NÃO CONFORME','NÃO APLICÁVEL','AÇÃO REQUERIDA PARA NÃO CONFORME'];
 function tableHeader(){heading(layout.sectionTitle,14);let x=left;headerLabels.forEach((label,n)=>{rect(x,y,columns[n],25,grey);text(label,x+3,y-3,6.1,columns[n]-6,bold);x+=columns[n];});y-=25;}
 let itemSize=7;function rowHeight(item){return item?Math.max(12,wrap(item.text,itemSize,columns[1]-6).length*(itemSize+1)+4):10;}
 const available=y-14-25-90,totalAt=()=>r.model.items.reduce((sum,i)=>sum+rowHeight(i),0)+(layout.totalRows-r.model.items.length)*10;
 while(totalAt()>available&&itemSize>6.0)itemSize-=.1;
 tableHeader();for(let n=0;n<layout.totalRows;n++){const item=r.model.items[n],answer=r.answers[n],h=rowHeight(item);if(y-h<62){newPage();heading(layout.annexTitle+' - continuação',17);tableHeader();}let x=left;for(const w of columns){rect(x,y,w,h);x+=w;}text(item?.sourceNumber||n+1,left+3,y-4,6.2,columns[0]-6);if(item){text(item.text,left+columns[0]+3,y-3,itemSize,columns[1]-6);const selected=['Conforme','Não Conforme','Não Aplicável'].indexOf(answer.value);if(selected>=0){const offset=columns.slice(0,selected+2).reduce((s,w)=>s+w,0);page.drawText('X',{x:left+offset+(columns[selected+2]-bold.widthOfTextAtSize('X',9))/2,y:y-h/2-3,size:9,font:bold});}const start=columns.slice(0,5).reduce((s,w)=>s+w,0);const actionLines=wrap(item.action||layout.action,6.2,columns[5]-6,bold);const top=y-(h-actionLines.length*7.2)/2;actionLines.forEach((line,j)=>text(line,left+start+3,top-j*7.2,6.2,columns[5]-6,bold));}y-=h;}
 let observation=[r.fields.notes||'',...r.answers.flatMap((a,n)=>a.notes?['Item '+(n+1)+': '+a.notes]:[])].filter(Boolean).join('\n');const observationHeight=Math.max(24,wrap(observation,6.3,width-8).length*7.3+15);if(y-observationHeight<40){newPage();heading('OBSERVAÇÕES',17);}const part=Math.min(observationHeight,y-42);rect(left,y,width,part);text('Observações:',left+4,y-3,6.3,width-8,bold);let lines=wrap(observation,6.3,width-8),capacity=Math.max(0,Math.floor((part-15)/7.3));lines.slice(0,capacity).forEach((line,n)=>text(line,left+4,y-14-n*7.3,6.3,width-8));lines=lines.slice(capacity);while(lines.length){newPage();heading('OBSERVAÇÕES - continuação',17);const cap=Math.floor((y-62)/8);lines.slice(0,cap).forEach((line,n)=>text(line,left+4,y-10-n*8,6.3,width-8));lines=lines.slice(cap);}
 newPage();heading('IDENTIFICAÇÃO E EVIDÊNCIAS DO REGISTRO',18);y-=12;text('Responsável: '+r.fields.inspector+' | matrícula: '+r.fields.employee,left,y,9,width,bold);y-=28;text('Função: '+(r.fields.functionName||'Não informada')+' | unidade: '+(r.fields.unit||'Não informada')+' | equipe: '+(r.fields.team||'Não informada'),left,y,8,width);y-=24;text('Registrado: '+localTime(r.recordedAt||r.updatedAt||r.createdAt)+' | Fuso: America/Fortaleza',left,y,8,width);y-=25;
 const top=y,boxH=220,boxW=259;rect(left,top,boxW,boxH);rect(left+272,top,boxW,boxH);text('ASSINATURA ELETRÔNICA DESENHADA',left+8,top-8,7.2,boxW-16,bold);text('REGISTRO FOTOGRÁFICO DO COLABORADOR',left+280,top-8,7.2,boxW-16,bold);
 async function image(data){return data.startsWith('data:image/png;')?doc.embedPng(data):doc.embedJpg(data);}
 if(r.signature?.data){const im=await image(r.signature.data),sz=im.scale(Math.min(242/im.width,145/im.height));page.drawImage(im,{x:left+8+(242-sz.width)/2,y:top-180+(145-sz.height)/2,width:sz.width,height:sz.height});text('Sem certificado digital',left+8,top-198,7,boxW-16);}
 if(r.workerPhoto?.data){const im=await image(r.workerPhoto.data),sz=im.scale(Math.min(242/im.width,175/im.height));page.drawImage(im,{x:left+280+(242-sz.width)/2,y:top-194+(175-sz.height)/2,width:sz.width,height:sz.height});}
 y=top-boxH-18;text('Elaborador do aplicativo: Paulo Ricardo Reis',left,y,8,width);y-=22;text('Documento preenchido a partir do modelo '+r.model.id+' | versão '+r.model.version,left,y,7,width);y-=22;text('As orientações e ações do procedimento de origem permanecem aplicáveis. Este registro não libera automaticamente o equipamento.',left,y,8,width);
 const evidence=r.answers.flatMap((a,n)=>a.photos.map(photo=>({photo,number:n+1})));for(let offset=0;offset<evidence.length;offset+=4){newPage();heading('EVIDÊNCIAS FOTOGRÁFICAS - até 4 fotos por página',18);for(let j=0;j<Math.min(4,evidence.length-offset);j++){const e=evidence[offset+j],x=left+(j%2)*272,top=727-Math.floor(j/2)*315;rect(x,top,259,296);text('Foto '+(offset+j+1)+' | Item '+e.number,x+8,top-8,8,243,bold);const im=await image(e.photo.data),sz=im.scale(Math.min(243/im.width,244/im.height));page.drawImage(im,{x:x+8+(243-sz.width)/2,y:top-272+(244-sz.height)/2,width:sz.width,height:sz.height});text(e.photo.name,x+8,top-278,6.5,243);}}
 doc.setTitle((r.company?.name||'PPL Manutenção')+' - '+layout.annexTitle+' - '+r.id);doc.setSubject(layout.procedureCode+' | revisão '+layout.revision);return doc.save();
}
